// 0: Print
// 1: Web Design
// 2: Motion
// 3: Logotype
// 4: WordPress

export default [
  {
    id: 0,
    img: "black",
    tag: 0,
    Text: "Stationary Branding #1",
    SubText: "Featured. Logotype. Print",
  },
  {
    id: 1,
    img: "white",
    tag: 1,
    Text: "Shadow – WP Theme",
    SubText: "Web Design, Wordpress",
  },
  {
    id: 2,
    img: "blue",
    tag: 2,
    Text: "Huge – WP Theme",
    SubText: "Logotype, Wordpress",
  },
  {
    id: 3,
    img: "darkgrey",
    tag: 0,
    Text: "Wowway – WP Theme",
    SubText: "Web Design, Wordpress",
  },
  {
    id: 4,
    img: "lightgrey",
    tag: 1,
    Text: "Password Protected",
    SubText: "Print",
  },
  {
    id: 5,
    img: "green",
    tag: 2,
    Text: "Soundcloud",
    SubText: "Web Design",
  },
  { id: 6, img: "yellow", tag: 3, Text: "Custom Link", SubText: "Motion" },
  {
    id: 7,
    img: "purple",
    tag: 0,
    Text: "Lovely Charts",
    SubText: "Motion, Web Design",
  },
  {
    id: 8,
    img: "red",
    tag: 1,
    Text: "Better Packaging",
    SubText: "Print",
  },
  {
    id: 9,
    img: "white",
    tag: 2,
    Text: "Just Packaging",
    SubText: "Web Design",
  },
  {
    id: 10,
    img: "yellow",
    tag: 3,
    Text: "Flat Icons #1",
    SubText: "Logotype",
  },
  {
    id: 11,
    img: "black",
    tag: 0,
    Text: "Stationary Branding #2",
    SubText: "Print",
  },
  {
    id: 12,
    img: "white",
    tag: 1,
    Text: "Improbable Identity",
    SubText: "Logotype",
  },
  {
    id: 13,
    img: "blue",
    tag: 2,
    Text: "In My New World",
    SubText: "Motion",
  },
  { id: 14, img: "grey", tag: 0, Text: "Flat Icons #2", SubText: "Print" },
  {
    id: 15,
    img: "lightgrey",
    tag: 1,
    Text: "Move",
    SubText: "Motion, Web Design",
  },
  {
    id: 16,
    img: "green",
    tag: 2,
    Text: "Perfect Packaging",
    SubText: "Logotype, Print",
  },
  {
    id: 17,
    img: "purple",
    tag: 0,
    Text: "Business Cards",
    SubText: "Logotype, Print",
  },
  { id: 18, img: "blue", tag: 1, Text: "More Videos", SubText: "Motion" },
  {
    id: 19,
    img: "black",
    tag: 2,
    Text: "Self Hosted Video",
    SubText: "Motion",
  },
];
