export default [
  { id: 0, img: "black", tag: "one" },
  { id: 1, img: "white", tag: "two" },
  { id: 2, img: "blue", tag: "three" },
  { id: 3, img: "grey", tag: "four" },
  { id: 4, img: "lightgrey", tag: "five" },
  { id: 5, img: "green", tag: "one" },
  { id: 6, img: "yellow", tag: "two" },
  { id: 7, img: "purple", tag: "three" },
  { id: 8, img: "red", tag: "four" },
  { id: 9, img: "white", tag: "five" },
  { id: 10, img: "yellow", tag: "one" },
  { id: 11, img: "black", tag: "two" },
  { id: 12, img: "white", tag: "three" },
  { id: 13, img: "blue", tag: "four" },
  { id: 14, img: "grey", tag: "five" },
  { id: 15, img: "lightgrey", tag: "one" },
  { id: 16, img: "green", tag: "two" },
  { id: 17, img: "purple", tag: "three" },
  { id: 18, img: "green", tag: "four" },
  { id: 19, img: "black", tag: "five" },
];
